name: Build iOS IPA

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # 允许手动触发

jobs:
  build_ios:
    name: Build iOS IPA
    runs-on: macos-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.6'
        channel: 'stable'
        cache: true
    
    - name: Install Flutter dependencies
      run: flutter pub get
    
    - name: Analyze Flutter code
      run: flutter analyze
      continue-on-error: true  # 即使有警告也继续构建
    
    - name: Setup iOS dependencies
      run: |
        cd ios
        pod install
        cd ..
    
    - name: Clean Flutter build
      run: flutter clean
    
    - name: Build iOS Debug (No Code Sign)
      run: flutter build ios --debug --no-codesign
    
    - name: Create IPA from iOS build
      run: |
        cd build/ios/iphoneos
        mkdir -p Payload
        cp -r Runner.app Payload/
        zip -r ../../../Runner-Debug.ipa Payload/
        cd ../../..
    
    - name: Build iOS Release (No Code Sign)
      run: flutter build ios --release --no-codesign
      continue-on-error: true
    
    - name: Create Release IPA from iOS build
      run: |
        cd build/ios/iphoneos
        mkdir -p Payload
        cp -r Runner.app Payload/
        zip -r ../../../Runner-Release.ipa Payload/
        cd ../../..
      continue-on-error: true
    
    - name: Upload Debug IPA
      uses: actions/upload-artifact@v4
      with:
        name: iOS-Debug-IPA
        path: Runner-Debug.ipa
        retention-days: 30
    
    - name: Upload Release IPA
      uses: actions/upload-artifact@v4
      with:
        name: iOS-Release-IPA
        path: Runner-Release.ipa
        retention-days: 30
      continue-on-error: true
    
    - name: Upload build logs
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: iOS-Build-Logs
        path: |
          build/ios/
          ios/Pods/
        retention-days: 7
