name: Build Android APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # 允许手动触发

jobs:
  build_android:
    name: Build Android APK
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.27.1'
        channel: 'stable'
        cache: false  # 禁用缓存，强制使用新版本
    
    - name: Verify Flutter version
      run: flutter --version
    
    - name: Install Flutter dependencies
      run: flutter pub get
    
    - name: Analyze Flutter code
      run: flutter analyze
      continue-on-error: true
    
    - name: Clean Flutter build
      run: flutter clean
    
    - name: Build Android Debug APK
      run: flutter build apk --debug
    
    - name: Build Android Release APK
      run: flutter build apk --release
    
    - name: Upload Debug APK
      uses: actions/upload-artifact@v4
      with:
        name: Android-Debug-APK
        path: build/app/outputs/flutter-apk/app-debug.apk
        retention-days: 30
    
    - name: Upload Release APK (beimo.apk)
      uses: actions/upload-artifact@v4
      with:
        name: Android-Release-APK-beimo
        path: build/app/outputs/flutter-apk/app-release.apk
        retention-days: 30
    
    - name: Upload build logs
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: Android-Build-Logs
        path: |
          build/
          android/
        retention-days: 7
